
import React from 'react';
import { GALLERY_ITEMS, GalleryItem } from '../data/galleryData.ts';
import { RemixConfig } from '../App.tsx';
import { SparklesIcon } from '../components/icons/SparklesIcon.tsx';

interface GalleryPageProps {
  onRemix: (config: RemixConfig) => void;
}

const GalleryPage: React.FC<GalleryPageProps> = ({ onRemix }) => {

  const handleRemixClick = (item: GalleryItem) => {
    const { image, title, description, ...remixConfig } = item;
    onRemix(remixConfig);
  }

  return (
    <div className="h-full overflow-y-auto custom-scrollbar">
      <main className="container mx-auto px-4 py-12 pt-20 md:py-16 md:pt-24">
        <div className="max-w-7xl mx-auto text-center">
          <h2 className="text-5xl md:text-8xl font-bold font-playfair mb-8 text-white tracking-tighter">Style Gallery</h2>
          <div className="w-24 h-1 bg-amber-500 mx-auto mb-8 rounded-full"></div>
          <p className="text-lg md:text-xl text-zinc-400 mb-16 max-w-2xl mx-auto font-light leading-relaxed">
            Curated designs generated by our engine. Select a look to remix it with your own photo using our semantic transfer technology.
          </p>
          
          {GALLERY_ITEMS.length > 0 ? (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
              {GALLERY_ITEMS.map((item, index) => (
                <div key={index} className="group relative bg-zinc-900/20 backdrop-blur-md rounded-sm border border-white/5 overflow-hidden text-left hover:border-amber-500/30 transition-all duration-700 hover:-translate-y-2 shadow-2xl">
                  <div className="aspect-w-3 aspect-h-4 relative">
                    <img src={item.image} alt={item.title} className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-110 opacity-90 group-hover:opacity-100 grayscale-[20%] group-hover:grayscale-0" />
                    <div className="absolute inset-0 bg-gradient-to-t from-zinc-950 via-zinc-950/20 to-transparent opacity-90"></div>
                  </div>
                  
                  <div className="absolute bottom-0 left-0 p-8 w-full flex flex-col justify-end">
                    <div className="transform transition-transform duration-500 translate-y-4 group-hover:translate-y-0">
                        <h3 className="text-3xl font-bold text-white font-playfair mb-3">{item.title}</h3>
                        <p className="text-sm text-zinc-400 mb-8 line-clamp-2 group-hover:text-zinc-200 transition-colors font-light">{item.description}</p>
                        <button 
                          onClick={() => handleRemixClick(item)}
                          className="w-full bg-white/5 hover:bg-amber-500 hover:text-black text-white border border-white/10 hover:border-amber-500 font-bold py-4 px-6 rounded-sm flex items-center justify-center gap-2 transition-all duration-300 text-xs uppercase tracking-[0.2em] backdrop-blur-xl"
                        >
                          <SparklesIcon className="w-4 h-4" />
                          Remix Look
                        </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="p-12 bg-zinc-900/50 border border-zinc-800 rounded-sm backdrop-blur-md">
                 <p className="text-zinc-500">The gallery is currently empty.</p>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default GalleryPage;
